services:
    #baby.logger_factory:
        #class: BabyBundle\Service\LogManagerFactory
    baby.logger:
        class: BabyBundle\Service\LogManager
        #factory: ["@baby.logger_factory", createLogManager]
        arguments: ["@request_stack"]
    baby.listener:
        class: BabyBundle\EventListener\BabyListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: baby.newplayer, method: logNewPlayer }
    baby.subscriber:
        class: BabyBundle\EventListener\BabySubscriber
        tags:
            - { name: kernel.event_subscriber }
    baby.exportcsv:
        class: BabyBundle\Service\CSVExportManager
    baby.export.event.subscriber:
        class: BabyBundle\EventListener\BabyExportSubscriber
        arguments: ["@mailer","@templating"]
        tags:
            - { name: kernel.event_subscriber }
