<?php

namespace BabyBundle\Repository;
use Doctrine\ORM\Query\Expr\Orx;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends \Doctrine\ORM\EntityRepository
{
  public function findTeamName($joueur){
    $teams = $this->_em->getRepository('BabyBundle:Team')->findTeamByPlayer($joueur->getId());
    foreach($teams as $team){
      $team_id[] = $team['id'];
    }
    if(!empty($team_id)){
       $query = $this->_em->createQuery('SELECT team.name FROM BabyBundle:Team team WHERE team.id IN (:team_id)');
       $query->setParameter('team_id', $team_id);
       $resultats = $query->getResult();
      return $resultats;
    }
  }
}
