<?php

namespace BabyBundle\Repository;

use BabyBundle\Entity\Joueur;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPlayerByTeam($team_id)
	{
		$query = $this->_em
				->createQuery('SELECT t FROM BabyBundle:Team t WHERE t.id = :team_id');
		$query->setParameter('team_id', $team_id);
		$results = $query->getResult();	
		return $results;
	}

	public function getPlayersByTeam($id_team)
	{
		$query = $this->createQueryBuilder('team');
		$query->select('team.id', 'team.name')
			->leftjoin('team.players', 'tp')
			->addSelect('tp.nom')
			->where('team.id=:id');
		$query->setParameter('id', $id_team);
		$result = $query->getQuery()
				->getResult();
		return $result;
	} 
}
