<?php

namespace BabyBundle\Repository;

/**
 * TournoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournoiRepository extends \Doctrine\ORM\EntityRepository
{
	public function findTeamsByTournament($id) 
	{	
		$query = $this->createQueryBuilder('tournoi');
		$query->select('tournoi.name')
			->leftjoin('tournoi.tournamentTeams', 'tt')
			->addSelect('tt.id')
			->where('tournoi.id=:id');
		$query->setParameter('id', $id);
		$results = $query->getQuery()
				 ->getResult();
		foreach($results as $team_id)
		{
			$teams[] = $this->_em->getRepository('BabyBundle:Team')->findOneById($team_id);
		}
		return $teams;
	}

}
